# Generated by Django 3.2.20 on 2023-10-04 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnitin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnitinsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
